name: Scrape Telegram for V2Ray Configs

on:
  schedule:
    # Runs every hour, on the hour.
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Wait for a random time (0 to 15 minutes)
        run: sleep $((RANDOM % 900))

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        # Installs all required packages for the v6 script
        run: pip install telethon geoip2 dnspython

      - name: Run Python Scraper
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✅ Automated Telegram Config & Category Update"
          # This pattern commits all changed files, including the state file and categories
          file_pattern: .
