# FILE: runner.yml (for your SECOND repo: v2ray-refiner)
# UPDATED SCRIPT (Runs every 30 minutes)

name: Refine V2Ray Configs

on:
  schedule:
    ### MODIFIED ### - Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 180

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✅ Refined, Categorized & Renamed Configs (IP Converted)"
